---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: debian-8.6
  - name: centos-7.3
  - name: fedora-25

suites:
- name: alltherubies
  run_list:
  - recipe[ruby_install]
  - recipe[alltherubies]
- name: installation
  run_list:
  - recipe[ruby_install]
- name: partial_ruby_version
  run_list:
  - recipe[ruby_install]
  - recipe[partial_ruby_version]
